"""
Photagger — Session report generation (HTML & CSV).
Produces summary reports after batch processing sessions.
"""
import csv
import time
from pathlib import Path
from .logger import get_logger

log = get_logger("report")


def generate_html_report(stats: dict, entries: list[dict], output_path: str | Path) -> str:
    """Generate a styled HTML session report."""
    output_path = Path(output_path)
    duration = stats.get("duration", 0)
    mins, secs = divmod(int(duration), 60)

    cat_rows = ""
    categories = stats.get("categories", {})
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        pct = (count / max(stats["total_accepted"], 1)) * 100
        cat_rows += f"""
        <tr>
            <td>{cat.capitalize()}</td>
            <td>{count}</td>
            <td><div class="bar" style="width:{pct:.0f}%">{pct:.0f}%</div></td>
        </tr>"""

    entry_rows = ""
    for e in entries[:200]:
        tags = e.get("tags", "")
        status_cls = "accepted" if e.get("status") == "accepted" else "rejected"
        entry_rows += f"""
        <tr class="{status_cls}">
            <td>{e.get('filename', '')}</td>
            <td>{e.get('status', '').upper()}</td>
            <td>{e.get('blur_score', 0):.1f}</td>
            <td>{e.get('exposure_score', 0):.1f}</td>
            <td>{"⭐" * e.get('star_rating', 0)}</td>
            <td>{e.get('category', '')}</td>
            <td class="tags">{tags}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Photagger Session Report</title>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:'Segoe UI',system-ui,sans-serif; background:#0F0F14; color:#E8E8ED; padding:40px; }}
  h1 {{ color:#6C63FF; font-size:28px; margin-bottom:8px; }}
  .subtitle {{ color:#8888A0; margin-bottom:32px; }}
  .stats {{ display:flex; gap:16px; margin-bottom:32px; }}
  .stat-card {{ background:#1A1A24; border:1px solid #2A2A3A; border-radius:12px; padding:20px; flex:1; text-align:center; }}
  .stat-card .number {{ font-size:36px; font-weight:700; color:#6C63FF; }}
  .stat-card .label {{ color:#8888A0; font-size:13px; margin-top:4px; }}
  .stat-card.success .number {{ color:#4ADE80; }}
  .stat-card.danger .number {{ color:#F87171; }}
  table {{ width:100%; border-collapse:collapse; background:#1A1A24; border-radius:12px; overflow:hidden; margin-bottom:32px; }}
  th {{ background:#22222E; padding:12px 16px; text-align:left; color:#8888A0; font-size:12px; text-transform:uppercase; letter-spacing:1px; }}
  td {{ padding:10px 16px; border-bottom:1px solid #2A2A3A; font-size:13px; }}
  tr.rejected td {{ opacity:0.5; }}
  .tags {{ color:#8888A0; font-size:11px; }}
  .bar {{ background:#6C63FF; color:white; padding:2px 8px; border-radius:4px; font-size:11px; min-width:30px; text-align:center; }}
</style>
</head>
<body>
<h1>📸 Photagger Session Report</h1>
<p class="subtitle">Generated {time.strftime('%B %d, %Y at %H:%M')} · Duration: {mins}m {secs}s</p>

<div class="stats">
  <div class="stat-card"><div class="number">{stats.get('total_processed',0)}</div><div class="label">Total Processed</div></div>
  <div class="stat-card success"><div class="number">{stats.get('total_accepted',0)}</div><div class="label">Accepted</div></div>
  <div class="stat-card danger"><div class="number">{stats.get('total_rejected',0)}</div><div class="label">Rejected</div></div>
</div>

<h2 style="margin-bottom:12px; font-size:18px;">Category Breakdown</h2>
<table><thead><tr><th>Category</th><th>Count</th><th>Distribution</th></tr></thead>
<tbody>{cat_rows}</tbody></table>

<h2 style="margin-bottom:12px; font-size:18px;">Processing Details</h2>
<table><thead><tr><th>Filename</th><th>Status</th><th>Blur</th><th>Exposure</th><th>Rating</th><th>Category</th><th>Tags</th></tr></thead>
<tbody>{entry_rows}</tbody></table>

<p style="color:#555570; text-align:center; margin-top:40px; font-size:12px;">Generated by Photagger v1.0.0</p>
</body></html>"""

    report_file = output_path / f"photagger_report_{int(time.time())}.html"
    report_file.write_text(html, encoding="utf-8")
    log.info(f"HTML report saved: {report_file}")
    return str(report_file)


def generate_csv_report(entries: list[dict], output_path: str | Path) -> str:
    """Generate a CSV export of all processing entries."""
    output_path = Path(output_path)
    csv_file = output_path / f"photagger_report_{int(time.time())}.csv"

    fieldnames = ["filename", "status", "blur_score", "exposure_score",
                  "star_rating", "category", "tags", "exif_summary", "timestamp"]

    with open(csv_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for entry in entries:
            writer.writerow(entry)

    log.info(f"CSV report saved: {csv_file}")
    return str(csv_file)
